---
- hosts: webservers
  vars:
      mysql_root_password: root
  tasks:
      - name: install packages
        become: yes
        apt:
            pkg:
                   - php-cli
                   - php-xml
                   - php-pgsql
                   - libapache2-mod-php
                   - php-curl
                   - apache2
                   - git
                   - zip
                   - unzip
                   - curl
            state: latest
            update_cache: yes

      - name: download composer installer
        get_url:
            url: https://getcomposer.org/installer
            dest: /tmp/composer

      - name: install composer
        shell: php /tmp/composer --install-dir=/usr/local/bin
        become: yes

      - name: rename composer executable
        shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
        become: yes

      - name: set permissions for composer file
        file:
            path: /usr/local/bin/composer
            mode: a+x
            state: file
        become: yes

      - name: start and enable mysql service
        service:
           name: mysql
           state: started
           enabled: yes
      
      - name: ceating mysql user
        mysql_user:
           name: "ubuntu"
           password: "?Barraghan74"
           priv: '*.*:ALL'
           host: '%'
           state: present

      - name: clone laravel codebase
        git:
            repo: https://github.com/f1amy/laravel-realworld-example-app.git
            dest: /var/www/laravel
        become: yes

      - name: take ownership of laravel folder
        file:
            path: /var/www/laravel
            owner: "{{ ansible_effective_user_id }}"
            group: "{{ ansible_effective_group_id }}"
            mode: '0777'
        become: yes
    
      - name: set permissions for Laravel storage folder
        file:
            path: /var/www/laravel/storage
            state: directory
            recurse: yes
            mode: '0777'
        become: yes

      - name: install laravel dependencies
        composer:
            command: install
            working_dir: /var/www/laravel

      - name: copy env file
        copy:
            src: /var/www/laravel/.env.example
            remote_src: yes
            dest: /var/www/laravel/.env
            owner: "{{ ansible_effective_user_id }}"
            group: "{{ ansible_effective_group_id }}"
            mode: '0777'
        become: yes

      - name: copy apache config
        copy:
            src: stubs/laravel.conf
            dest: /etc/apache2/sites-available/laravel.conf
            owner: "{{ ansible_effective_user_id }}"
            group: "{{ ansible_effective_group_id }}"
            mode: '0777'
        become: yes

      - name: set server name
        replace:
            path: /etc/apache2/sites-available/laravel.conf
            regexp: '$SERVER_NAME'
            replace: '{{ ansible_host }}'
        become: yes

      - name: enable the new config
        shell: |
            a2ensite laravel.conf
            a2dissite 000-default.conf
            a2enmod rewrite
            service apache2 restart
        become: yes

      - name: setup laravel
        shell: |
            cd /var/www/laravel
            php artisan key:generate
        become: yes

#   roles:
#     - { role: geerlingguy.mysql }
